config/routes.rb
Promosite::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'
  match '/signin' => 'authentications#new', :as => :signin
  match '/auth/failure' => 'authentications#failure'
  devise_for :admins
  devise_for :users, :controllers => {:registrations => 'user_registrations'}
  devise_for :merchants, :controllers => {
    :registrations => 'merchant_registrations'}

  resources :authentications
  resources :cities
  resources :classifications
  resources :merchants do
    resources :branches
    resources :promos do
      post :claim, :on => :member
      put :redeem, :on => :member
      match '/print', :to => 'promos#print', :on => :member
    end
  end

  match '/privacy',      :to => 'pages#privacy'
  match '/term_use',     :to => 'pages#term_use'
  match '/term_sale',    :to => 'pages#term_sale'
  match '/how_it_works', :to => 'pages#how_it_works'
  
  match '/my_promos',  :to => 'promos#track',   :as => 'claimed_promos'
  match '/my_tracker', :to => 'promos#records', :as => 'promo_records'

  match 'promos/:classification', :to => 'promos#index',
    :as => 'classified_promos'
  
  match '/merchants/classified-as/:classification',
    :to => 'merchants#index',
    :as => 'classified_merchants' 

  root :to => "promos#index"
end

app/models/merchant.rb
require 'carrierwave/mongoid'
require 'filsale_validator'
require 'will_paginate/array' 

class Merchant
  include Mongoid::Document
  include Mongoid::Timestamps
  include FilsaleValidator

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  field :name,      :type => String
  field :info,      :type => String
  field :featured,  :type => Boolean, :default => false
  field :agree,     :type => Boolean
  field :permalink, :type => String
  mount_uploader    :image, ImageUploader

  validates :name,      :presence => true, :uniqueness => true
  validates :info,      :presence => true, :length => { :maximum => 250 }
  validates :email,     :email_unique_in_filsale => true
  validates :permalink, :uniqueness => true

  references_many :branches, :dependent => :destroy
  references_many :promos,   :dependent => :destroy
  references_and_referenced_in_many :classifications, inverse_of: :merchants

  index :permalink, :unique => true

  before_validation do |merchant|
    merchant.email.downcase!
  end

  before_save do |merchant|
    self.permalink = self.name.parameterize
  end

  def to_param
    self.permalink
  end

  def set_classifications( classifications )
    self.classifications.each do |c|
      c.merchant_ids.delete self.id
      c.save!
    end

    self.classification_ids = []
    self.classifications = classifications
    self.save!
  end

  def self.classified_as( classification, page, per_page )
    if classification.nil?
      all.asc(:name).paginate(:page => page, :per_page => per_page)
    else
      classification = Classification.where(:permalink => classification).first
      classification.merchants.paginate(:page => page, :per_page => per_page)
    end
  end

  def featured?
    self.featured
  end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController

  def index
    @title = 'All Merchants'
    @classifications = Classification.all
    @merchants = Merchant.classified_as( params[:classification],
      params[:page], 5 )
  end

  def show
    @merchant = Merchant.where(:permalink => params[:id]).first
    @title = @merchant.name
  end

  def new
    @merchant = Merchant.new

    @title = 'Merchant Signup'
    @classifications = Classification.all
  end

  def edit
    @merchant = Merchant.where(:permalink => params[:id]).first

    @title = 'Edit Merchant'
    @classifications = Classification.all
  end

  def create
    @merchant = Merchant.new(params[:merchant])
    if @merchant.save
      @merchant.set_classifications( checked_classifications )
      flash[:notice] = 'Merchant ' + @merchant.name  + ' was created.'
      redirect_to @merchant
    else
      @title = 'Merchant Signup'
      render :action => "new"
    end
  end

  def update
    @merchant = Merchant.where(:permalink => params[:id]).first
    if @merchant.update_attributes(params[:merchant])
      @merchant.set_classifications( checked_classifications )
      flash[:notice] = 'Merchant ' + @merchant.name  + ' was updated.'
      redirect_to @merchant
    else
      render :action => "edit"
    end
  end

  def destroy
    @merchant = Merchant.where(:permalink => params[:id]).first
    @merchant.destroy
    redirect_to(merchants_url)
  end

  private

  def checked_classifications
    return [] unless params[:classifications]

    checked = []
    params[:classifications].map do |key, value|
      checked << Classification.find( key )
    end
    checked
  end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
  def heading_for_new_merchant
    if admin_signed_in?
      "Create merchant"
    else
      "Merchant Signup"
    end
  end

  def image_for_merchant(merchant)
    if merchant.image.url
      image_tag merchant.image.url
    else
      image_tag "merchant.default.png"
    end
  end
end

app/views/merchants/_branch_field.html.erb
<h2>Branches</h2>
<table class="data">
  <thead>
    <tr>
      <th>Branch</th>
      <th>Address</th>
      <th>City</th>
      <th>Contact Number</th>
      <% if admin_signed_in? || @merchant == current_merchant %>
        <th>Actions</th>
        <th>Update</th>
      <% end %>
    </tr>
  </thead> 
  <tbody>
    <% @merchant.branches.each do |branch| %>
      <tr>
        <td><%= branch.name %></td>
        <td><%= branch.address %></td>
        <td><%= branch.city.name %></td>
        <td><%= branch.contact_number %></td>
        <% if admin_signed_in? || @merchant == current_merchant %>
          <td>
            <%= link_to(image_tag("/images/carbon/silk/cross.png"), [branch.merchant, branch], :confirm => "Are you sure you want to delete this branch?\n* #{branch.name}", :method => :delete) %>
          </td>
          <td>
            <%= link_to 'Edit', edit_merchant_branch_path(branch.merchant, branch) %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% if admin_signed_in? || @merchant == current_merchant %>
  <br>
  <p>
    <%= link_to image_tag("/images/carbon/silk/add.png"), new_merchant_branch_path(@merchant) %>
  </p>
<% end %>

app/views/merchants/_branch_form.html.erb
<h4>Add a branch:</h4>                
<%= form_for([@merchant, @merchant.branches.build]) do |f| %>
  <div class="field">                 
    <%= f.label :name %><br />
    <%= f.text_field :name%>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= label_tag :city %><br />
    <%= select_tag :city, options_from_collection_for_select(@cities, 'id', 'name') %>
  </div>
  <div class="field">
    <%= f.label :contact_number %><br />
    <%= f.text_field :contact_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/merchants/_form.html.haml
%div#inline-form.portlet-content
  = form_for(@merchant, :html => { :multipart => true, :class => "form label-top"  }) do |f|
    = render :partial => 'shared/errors', :locals => {:resource => @merchant}

    -if params[:password]
      =render :partial => 'devise/registrations/password_form', :locals => {:f => f}
    -else
      .field
        = f.label :name
        = f.text_field :name

      .field
        = f.label :email
        = f.text_field :email

      .field
        = f.label :info
        = f.text_area :info, :rows => 5

      .field.checkbox
        = label_tag :business_type
        = render :partial => 'classifications/check_boxes', :locals => {:classified => @merchant}

      - if admin_signed_in?
        .field
          = f.check_box :featured
          = f.label :featured, "Is this a featured merchant?"

      %div{ :class => "field upload clearfix" }
        = f.label :logo
        = f.file_field :image
        = f.hidden_field :image_cache

      .field
        = f.label :password
        = f.password_field :password

      .field
        = f.label :password_confirmation
        = f.password_field :password_confirmation

    .buttonrow
      %button{ :onClick => "javascript:form.submit();" }
        %span Submit
      %button{ :class => "btn-sec"}
        %span Cancel

app/views/merchants/_merchant_field.html.erb
<table class="data plain">
  <tbody>
    <td style="width: 250px;"><%= image_tag(@merchant.image.url || '/images/merchant.default.png', :size => "200x130") %></td>
    <td>
      <h2><%= @merchant.name %></h2>
      <h4 color="black"><%= @merchant.info %></h4>
      <p><font color="#000000"><strong>Business Type:</strong>&nbsp; &nbsp; 
        <% @merchant.classifications.each do |c| %>
          <%= c.name %>
        <% end %>
      </p>
    </td>
  </tbody>
</table>

<% if admin_signed_in? || @merchant == current_merchant %>
  <%= link_to 'Edit', edit_merchant_path(@merchant) %>
<% end %>

<div class="portlet-header">
  <h4>Details</h4>
  <ul class="portlet-tab-nav">
    <li class="portlet-tab-nav-active"><a href="#tab1">Branches</a></li>
    <li ><a href="#tab2">Deals</a></li>
  </ul>
</div> <!-- .portlet-header -->
<div class="portlet-content">
  <div id="tab1" class="portlet-tab-content">
    <%= render "branch_field" %>
  </div>
  <div id="tab2" class="portlet-tab-content">
    <%= render "promo_field" %>
  </div>
</div>

app/views/merchants/_promo_field.html.haml
%h2
  Past Deals
  %br
  %br
  - if admin_signed_in? || @merchant == current_merchant
    = link_to image_tag("/images/carbon/silk/add.png"), new_merchant_promo_path(@merchant)
-@merchant.promos.desc(:countdown_period_start).each do |promo|
  -if admin_signed_in? || @merchant == current_merchant
    .deal-item-image-list#gallery3
      -image = promo.image.url || "/images/deal.default2.png"
      =link_to image_tag(image), image
    .merchant-deal-item#details
      %h3
        -if promo.rejected?
          %span{:style=>"color: red"}REJECTED: 
        =link_to("#{promo.percent_discounted}% OFF! Only P#{promo.price_discounted} for #{promo.name}", [promo.merchant, promo])
      %p=promo.details
      %p
        %strong Claimable on:
        =promo.period_start_new_format
        %strong Until:
        =promo.period_end_new_format
      %p
        %strong Coupon valid on:
        =promo.validity_start_new_format
        %strong Until:
        =promo.validity_end_new_format
      %p
        -if @promo_branches_count = 1
          %strong Participating branch: 
          =promo.branches.collect{ |b| b.name }.join(', ')
        -else
          %strong Participating branches:
          =promo.branches.collect{ |b| b.name }.join(', ')
      %p
        %strong Actual Price: P
        =promo.price_actual
        %nbsp;
        %strong Discounted Price: P
        =promo.price_discounted
        %nbsp;
        %strong Quota:
        =promo.quota
      %p
        %strong Code:
        =promo.manual_code || promo.random_code
      %p
        %strong= promo.rejected? ? "Action:" : "Actions"
        - unless promo.rejected?
          -if promo.editable?
            = link_to image_tag("/images/carbon/silk/pencil.png"),   [:edit, promo.merchant, promo]
          -else
            <img src="/images/carbon/silk/pencil.png">
        = link_to image_tag("/images/carbon/silk/cross.png"), [promo.merchant, promo], :confirm => "Are you sure you want to delete this deal?\n* #{promo.name}", :method => :delete
        -unless promo.editable?
          (This promo is active. Therefore it cannot be <img src="/images/carbon/silk/pencil.png">)
  -else
    -if promo.date_now >= promo.period_start && promo.date_now >= promo.period_end
      .deal-item-image-list#gallery3
        -image = promo.image.url || "/images/deal.default2.png"
        =link_to image_tag(image), image
      .merchant-deal-item#details
        %h3
          =link_to("#{promo.percent_discounted}% OFF! Only P#{promo.price_discounted} for #{promo.name}", [promo.merchant, promo])
        %p=promo.details
        %p
          %strong Claimable on:
          =promo.period_start_new_format
          %strong Until:
          =promo.period_end_new_format
        %p
          %strong Coupon valid on:
          =promo.validity_start_new_format
          %strong Until:
          =promo.validity_end_new_format
        %p
        -if @promo_branches_count = 1
          %strong Participating branch: 
          =promo.branches.collect{ |b| b.name }.join(', ')
        -else
          %strong Participating branches:
          =promo.branches.collect{ |b| b.name }.join(', ')

app/views/merchants/_promo_form.html.erb
<h4>Add a Promo:</h4>
<%= form_for([@merchant, @promo], :html => { :multipart => true, :class => "form label-top"  } ) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <% if admin_signed_in? %>
    <%= render :partial => 'promos/classification' %>
  <% end %>
  <div class="field upload clearfix">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details, :rows => 5 %>
  </div>
  <div class="field">
    <%= f.label :authenticator %><br />
    <%= f.text_field :manual_code %>
  </div>
  <div class="field">
    <%= f.label :start %><br />
    <%= f.date_select :start, :start_year => 2010, :end_year => 2020 %>
  </div>
  <div class="field">
    <%= f.label :end %><br />
    <%= f.date_select :expired, :start_year => 2010, :end_year => 2020 %>
  </div>
  <div class="field">
    <%= f.label :period %><br />
    <%= f.datetime_select :period, :start_year => 2010, :end_year => 2020 %>
  </div>
  <div class="field">
    <%= f.label :period_end %><br />
    <%= f.datetime_select :period_end, :start_year => 2010, :end_year => 2020 %>
  </div>
  <% if admin_signed_in? %>
    <div class="field">
      <%= f.label :status %><br />
      <%= f.radio_button :status, 1 %>Active
      <%= f.radio_button :status, 0 %>Inactive
    </div>
  <% end %>
  <div class="field">
    <%= f.label :price_actual %><br />
    <%= f.text_field :price_actual  %>
  </div>
  <div class="field">
    <%= f.label :price_discounted %><br />
    <%= f.text_field :price_discounted %>
  </div>
  <div class="field">
    <%= f.label :quota %><br />
    <%= f.text_field :quota %>
  </div>
  <% if admin_signed_in? %>
    <div class="field">
      <%= f.check_box :featured %>
      <%= f.label :featured, "Is this a featured promo?" %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :branch %><br />
    <% for branch in @merchant.branches %>
      <input id="promo_branch" name="promo[branch][]" type="checkbox" value="<%= branch.name %>" />
      <%= branch.name %><br />
    <% end %>
  </div>
  <div class="action">
    <%= f.submit %>
  </div>
<% end %>

app/views/merchants/edit.html.erb
<h3>Editing merchant</h3>
<%= render 'form' %>

<%= link_to 'Show', @merchant %> 
<% unless params[:password] %>
  | <%= link_to 'Back', merchants_path %>
  | <% link_to 'Change password', '?password=true' -%>
<% else %>
  | <%= link_to 'Back', [:edit, @merchant] %>
<% end %>

app/views/merchants/index.html.erb
<div class="portlet-header">
  <h4>Merchants</h4>
  <ul class="portlet-tab-nav">
    <%= link_to_collection 'All', merchants_path %>
    <% @classifications.each do |c| %>
      <%= link_to_collection c.name, classified_merchants_path(:classification => c.permalink), c.permalink  %>
    <% end %>
  </ul>
</div> <!-- .portlet-header -->

<div class="portlet-content">
  <div id="tab1" class="portlet-tab-content">

    <%= will_paginate %>
    
    <table class="data plain" cellspacing="0" cellpadding="0">
      <tbody>
        <% @merchants.each do |merchant| %>
          <tr class="odd">
            <td style="width: 250px;"><%= image_tag(merchant.image.url || '/images/merchant.default.png', :size => "200x130") %></td>
            <td>
              <h3><%= link_to merchant.name, merchant %></h3>
              <p><%= merchant.info %></p>
              <p><strong>Business Type:</strong>
                <% merchant.classifications.each do |c| %>
                  <%= c.name %>
                <% end %>
              </p>
            </td>
            <td>
              <% if admin_signed_in? %>
                &nbsp;<%= link_to image_tag("/images/carbon/silk/pencil.png"), edit_merchant_path(merchant) %>&nbsp;
                <%= link_to image_tag("/images/carbon/silk/cross.png"), merchant, :confirm => 'Are you sure?', :method => :delete %>
              <% end %>
              <% if merchant_signed_in? %>
                <% if merchant == current_merchant %>
                  &nbsp;<%= link_to image_tag("/images/carbon/silk/pencil.png"), edit_merchant_path(merchant) %>&nbsp;
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate %>
  </div>
</div>

<% if admin_signed_in? %>
  <p>
    <%= link_to image_tag("/images/carbon/silk/add.png"), new_merchant_path %>
  </p>
<% end %>

app/views/merchants/new.html.erb
<h3><%= heading_for_new_merchant %></h3>
<%= render :partial => 'merchants/form' %>
<%= link_to 'Back', merchants_path %>

app/views/merchants/show.html.erb
<h4>
  <%= link_to '[Back]', merchants_path %>
</h4>

<%= render "merchant_field" %>