config/routes.rb
Promosite::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'
  match '/signin' => 'authentications#new', :as => :signin
  match '/auth/failure' => 'authentications#failure'
  devise_for :admins
  devise_for :users, :controllers => {:registrations => 'user_registrations'}
  devise_for :merchants, :controllers => {
    :registrations => 'merchant_registrations'}

  resources :authentications
  resources :cities
  resources :classifications
  resources :merchants do
    resources :branches
    resources :promos do
      post :claim, :on => :member
      put :redeem, :on => :member
      match '/print', :to => 'promos#print', :on => :member
    end
  end

  match '/privacy',      :to => 'pages#privacy'
  match '/term_use',     :to => 'pages#term_use'
  match '/term_sale',    :to => 'pages#term_sale'
  match '/how_it_works', :to => 'pages#how_it_works'
  
  match '/my_promos',  :to => 'promos#track',   :as => 'claimed_promos'
  match '/my_tracker', :to => 'promos#records', :as => 'promo_records'

  match 'promos/:classification', :to => 'promos#index',
    :as => 'classified_promos'
  
  match '/merchants/classified-as/:classification',
    :to => 'merchants#index',
    :as => 'classified_merchants' 

  root :to => "promos#index"
end

app/models/promo.rb
require 'carrierwave/mongoid'
require 'will_paginate/array' 
class Promo
  include Mongoid::Document
  include Mongoid::Timestamps

  MIN_DISCOUNT_RATE = 0.2

  # Public fields
  field :name,                   :type => String
  field :permalink,              :type => String
  field :details,                :type => String
  field :manual_code,            :type => String
  field :status,                 :type => Symbol,  :default => :pending
  field :featured,               :type => Boolean, :default => false
  field :price_actual,           :type => Integer
  field :price_discounted,       :type => Integer
  field :quota,                  :type => Integer
  field :countdown_period_start, :type => DateTime
  field :countdown_period_end,   :type => DateTime
  field :coupon_validity_start,  :type => Date
  field :coupon_validity_end,    :type => Date

  # Scope
  scope :countdown_period_start , where(:order => "desc")
  # Associations
  referenced_in   :merchant
  references_many :promo_claims
  references_and_referenced_in_many :users, :inverse_of => :promos
  references_and_referenced_in_many :classifications,  :inverse_of => :promos
  references_and_referenced_in_many :branches,  :inverse_of => :promos

  # Mounted uploaders
  mount_uploader :image, ImageUploader

  # Indexes
  index :permalink, :unique => true
  
  # Private field
  field :_min_period_start, :type => Time, :default => 1.days.from_now

  # Validations
  validates :name,                   :presence => true
  validates :details,                :presence => true
  validates :countdown_period_start, :presence => true
  validates :countdown_period_end,   :presence => true
  validates :coupon_validity_start,  :presence => true
  validates :coupon_validity_end,    :presence => true
  validates :price_actual,           :presence => true
  validates :price_discounted,       :presence => true
  validate  :minimum_discount
  validate  :code_should_be_8_characters_or_nothing
  #validate  :branches_cannot_be_empty
  validate  :valid_countdown_period_start
  validate  :valid_countdown_period_end
  validate  :valid_coupon_validity_start
  validate  :min_validity_end

  # Scopes
  
  scope :ending_in_24_hours, where(:countdown_period_end.lte => 24.hours.from_now)
  scope :not_expired, where(:countdown_period_start.lte => Time.now,
                            :countdown_period_end.gte => Time.now,
                            :status => :active)
  scope :next_deal, where(:status => :active)
  scope :pending, where(:status => :pending)

  # Autosuggest period_start, period_end, and validity_start
  def initialize(options = nil, attributes = nil)
    super(options)
    self.countdown_period_start = options[:period_start] || min_period_start
    self.countdown_period_end   = options[:period_end]   || min_period_end
    self.coupon_validity_start  = 
    options[:coupon_validity_start]  || min_max_validity_start
  end

  # Create permalink just before saving
  before_save do |promo|
    promo.permalink = promo.name.parameterize
    promo.manual_code = Promo.random_code if promo.manual_code.blank?
  end

  def to_param
    self.permalink
  end

  # Remaining time til countdown period ends
  def countdown_time_left
    self.countdown_period_end.to_i - DateTime.now.to_i
  end
  
  def countdown_for_next_deal
    self.countdown_period_start.to_i - DateTime.now.to_i
  end

  def date_now
   date_now = DateTime.now
  end
  
  def self.find_next_items( merchant_id, permalink)
    promos = merchant_id ? self.where(:merchant_id => merchant_id) : all
    if permalink.nil?
      promos.next_deal.where(:countdown_period_start => {'$gt' => DateTime.now, '$lt' => 7.days.from_now}) 
    else
      c = Classification.where(:permalink => permalink).first
      c.promos.next_deal.where(:countdown_period_start => {'$gt' => DateTime.now, '$lt' => 7.days.from_now}) 
    end
  end
  
  def self.find_promo_items( merchant_id, permalink, page, per_page )
    promos = merchant_id ? self.where(:merchant_id => merchant_id) : all

    if permalink.nil?
      promos.not_expired.desc(:created_at).paginate(:page => page, :per_page => per_page)
    else
      c = Classification.where(:permalink => permalink).first
      c.promos.not_expired.desc(:created_at).paginate(:page => page, :per_page => per_page)
    end
  end

 # def set_classifications( classifications )
 #   set :classifications, classifications
  #end

  def set_branches( branches )
    set :branches, branches
  end

  def promo_valid?
    !quota_full? && Time.now < countdown_period_end
  end

  def quota_full?
    #(promo_claims.total_discounts == quota)
    (quota - promo_claims.count) <= 0
  end

  def discounts
    price_actual - price_discounted
  end

  def self.random_code
    alphanumerics = [('0'..'9'),('A'..'Z')].map {|range| range.to_a}.flatten
    (0...8).map { alphanumerics[Kernel.rand(alphanumerics.size)] }.join
  end

  def claim!(claiming_user)
    unless quota_full?
      unless claiming_user.claimed?(self)
        promo_claims.create({:manual_code => manual_code, :validity => expired, :user_id => claiming_user.id, :discounts => discounts})
      else
        raise "One claim per user!"
      end
    end
  end

  def featured?
    self.featured
  end

  def redeem(user_id)
    pc = promo_claims.where(:user_id => user_id).first
    pc.redeemed = true
    pc.save!
  end
  
  def percent_discounted
   ( discounts * 100 ) / price_actual 
  end

  def remaining
    total_claims - promo_claims.count
  end
  
  def total_claims
    if quota && discounts
      quota
    end
  end

  def editable?
    s = status
    s == :pending || s == :rejected
  end

  def status
    s = read_attribute(:status)
    if s == :active && countdown_period_end > Time.now
      :active
    elsif s == :active
      :recent
    else
      s # either pending or rejected
    end
  end

  def activate
    self.status = :active
  end

  def reject
    self.status = :rejected
  end

  def rejected?
    self.status == :rejected
  end
 




  private

  # hack for making many-to-many associations work in Mongoid 2 beta 20
  def set(resource, array)
    eval("self.#{resource}.each") do |r|
      r.promo_ids.delete self.id
      r.save
    end

    eval("self.#{resource.to_s.singularize}_ids = []")
    eval("self.#{resource} = array")
    self.save
  end

  def minimum_discount
    if price_actual && price_discounted
      return if discounts >= (price_actual * MIN_DISCOUNT_RATE)
      errors.add(:price_discounted, "must be at least #{MIN_DISCOUNT_RATE*100}% less than actual price")
    end
  end

  def code_should_be_8_characters_or_nothing
    return if manual_code.blank?
    errors.add(:manual_code, 'must be 8 characters or none') if manual_code.length != 8
  end

  def branches_cannot_be_empty
    errors.add(:branches, "can't be empty") if branches.blank?
  end

  def valid_countdown_period_start
    if countdown_period_start < _min_period_start
      errors.add(:countdown_period_start, 'must be at least 1 day from now')
    end
  end

  def valid_countdown_period_end
    if countdown_period_end < min_period_end
      errors.add(:countdown_period_end, 'must be at least 4 hours from countdown start')
    end
    if countdown_period_end > max_period_end
      errors.add(:countdown_period_end, 'must be at most 3 days from countdown start')
    end
  end

  def valid_coupon_validity_start
    if coupon_validity_start < min_max_validity_start
      errors.add(:coupon_validity_start, 'must be at least next day after promo countdown end')
    end
  end
  
public
  def min_period_start
    _min_period_start + 1.hour
  end

  def min_period_end
    countdown_period_start + 4.hours if countdown_period_start
  end

  def max_period_end
    countdown_period_start + 3.days if countdown_period_start
  end

  def min_max_validity_start
    (countdown_period_end + 1.day).to_date if countdown_period_end
  end

  def min_validity_end
    if coupon_validity_end && coupon_validity_start && coupon_validity_end <= coupon_validity_start
      errors.add(:expired, "Canot be less than or equal to validity start")
    end
  end





  public

  def period_start
    self.countdown_period_start.strftime("%Y-%m-%d %H:00")
  end
  
  def period_start_new_format
    self.countdown_period_start.strftime("%b %d, %Y %I:00 %p")
  end

  def period_start=(period_start)
    self.countdown_period_start = period_start
  end

  def period_end
    self.countdown_period_end.strftime("%Y-%m-%d %H:00")
  end

  def period_end=(period_end)
    self.countdown_period_end = period_end
  end

  def period_end_new_format
    self.countdown_period_end.strftime("%b %d, %Y %I:00 %p")
  end
  
  def validity_start_new_format
    self.coupon_validity_start.strftime("%b %d, %Y")
  end
  
  def validity_end_new_format
    self.coupon_validity_end.strftime("%b %d, %Y")
  end
  # Deprecated APIs

  def period
    self.countdown_period_start
  end

  def period=(period)
    self.countdown_period_start = period
  end

  def start
    self.coupon_validity_start
  end

  def start=(start)
    self.coupon_validity_start = start
  end

  def expired
    self.coupon_validity_end
  end

  def expired=(expired)
    self.coupon_validity_end = expired
  end

  deprecate :period
  deprecate :period=
  deprecate :start
  deprecate :start=
  deprecate :expired=
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
  before_filter :authenticate_user!, :only => [:claim, :track]
  before_filter :authenticate_merchant_or_admin, :only => :records
  
  def index
    @title = 'Deal list'
    if params[:merchant_id]
      merchant = Merchant.where(:permalink => params[:merchant_id]).first
      merchant_id = merchant.id
      @classifications = merchant.classifications
    elsif current_merchant
      merchant_id = current_merchant.id
      @classifications = current_merchant.classifications
    else
      @classifications = Classification.asc(:name)
    end
    @promos = Promo.find_promo_items(merchant_id, params[:classification],  params[:page], 5)
    @promocount = @promos.count
    @deals = @promos
    @promos_next = Promo.find_next_items(merchant_id, params[:classification]).asc(:countdown_period_start)
    @promos_next_count = @promos_next.count
    @promos_coming = @promos_next.first
    @dateage = Time.now.strftime('%Y %B %d %H %M')
    @tryme = Time.now.in_time_zone("Hong Kong")
    @try = @tryme.strftime('%Y %B %d %H %M')
  end

  def show
    @merchant = Merchant.where(:permalink => params[:merchant_id]).first
    @promo = @merchant.promos.where(:permalink => params[:id]).first
    @title = @promo.name
    @users = @promo.users
    @promo_branches_count = @promo.branches.count
    @time = Time.now.in_time_zone("Hong Kong")
  end

  def new
    @merchant = Merchant.where(:permalink => params[:merchant_id]).first
    @promo = @merchant.promos.build
    @classifications = @merchant.classifications
  end

  def edit
    @merchant = Merchant.where(:permalink => params[:merchant_id]).first
    @promo = @merchant.promos.where(:permalink => params[:id]).first
    @classifications = @merchant.classifications
  end

  def create
    @merchant = Merchant.where(:permalink => params[:merchant_id]).first
    @promo = @merchant.promos.build(params[:promo])

    override_period_start(@promo) if admin_signed_in?

    if @promo.set_branches checked_branches # promo automatically saved
      #@promo.set_classifications checked_classifications
      flash[:notice] = "Your new deal was successfully created and is pending for manual review by the Twiggzy team. You will be notified whether your deal was activated or rejected through email. Thank you for using Twiggzy."
      redirect_to merchant_path(@merchant)
    else
      @classifications = Classification.all
      render :action => 'new', :merchant_id => @merchant
    end
  end

  def override_period_start(promo)
    promo._min_period_start = Time.now.in_time_zone("Hong Kong")

    def promo.valid_countdown_period_start
      if countdown_period_start < _min_period_start
        errors.add(:countdown_period_start, 'must be greater than the current time')
      end
    end
  end

  def update
    @merchant = Merchant.where(:permalink => params[:merchant_id]).first
    @promo = @merchant.promos.where(:permalink => params[:id]).first

    override_period_start(@promo) if admin_signed_in?

    if params[:activate]
      @promo.activate
      PromoMailer.activate(@promo).deliver
      flash[:notice] = "Deal was activated. An email was sent notifying the merchant."
    elsif params[:reject]
      @promo.reject
      PromoMailer.reject(@promo).deliver
      flash[:notice] = "Deal was rejected. An email was sent notifying the merchant."
    end

    if @promo.update_attributes(params[:promo])
      @promo.set_classifications checked_classifications
      @promo.set_branches checked_branches
      flash[:notice] ||= "Deal was successfully updated."
      redirect_to merchant_path(@merchant)
    else
      render 'edit'
    end
  end
  
  def destroy
    @merchant = Merchant.where(:permalink => params[:merchant_id]).first
    @promo = @merchant.promos.where(:permalink => params[:id]).first
    @promo.destroy
    redirect_to merchant_path(@merchant)
  end

  def claim
    @promo = Promo.where(:permalink => params[:id]).first
    unless current_user.first_name.blank? && current_user.last_name.blank?
      @promo.claim!(current_user)
      flash[:notice] = "Print the coupon and present it when you will purchase the deal."
    else
      flash[:notice] = "You can't claim a deal unless your name is complete!"
    end
    redirect_to merchant_promo_path(@promo.merchant, @promo)
  end

  def track
    @promos = current_user.claimed_promos
  end

  def records
    @promos = if merchant_signed_in?
      current_merchant.promos
    else
      Promo.pending
    end
  end

  def redeem
    @promo = Promo.where(:permalink => params[:id]).first
    begin
      @promo.redeem(params[:user_id])
      flash[:notice] = "Redeemed already"
    ensure
      redirect_to merchant_promo_path(@promo.merchant, @promo)
    end
  end

  def print
    @merchant = Merchant.where(:permalink => params[:merchant_id]).first
    @promo = @merchant.promos.where(:permalink => params[:id]).first

    render :layout => false 
  end


  private

  def checked_classifications
    return [] unless params[:classifications]
    checked = []
    params[:classifications].map do |key, value|
      checked << Classification.find( key )
    end
    checked
  end

  def checked_branches
    return [] unless params[:branches]
    checked = []
    params[:branches].map do |key, value|
      checked << Branch.find( key )
    end
    checked
  end

  def authenticate_merchant_or_admin
    return true if admin_signed_in? || merchant_signed_in?
    authenticate_merchant!
  end
  
end

app/helpers/promos_helper.rb
module PromosHelper
  def checked_or_unchecked(classification, deal)
    deal.classification_ids.include?( classification.id ) ?
      check_box_tag("classifications[#{classification.id}]", 1, true) :
      check_box_tag("classifications[#{classification.id}]")
  end

  def image_for_deal(deal)
    deal.image.url || 'deal.default2.png'
  end
end

app/views/promos/_classification.html.haml
-if @classifications
  -classifications.each do |c|
    = checked_or_unchecked( c, @promo )
    %label{ :for => "classifications_#{c.id}"}= c.name
    %br

app/views/promos/_customer_form.html.erb
<% if user_signed_in? %>
  <% if current_user.claimed?(@promo) %>
    <table class="popups">
	  <tr>
		<td class="print_button">
         <%= link_to 'Print', print_merchant_promo_path, :class => "btnPrint" %>
        </td>
        <td class="popups">
      <%= link_to 'Coupon Preview', print_merchant_promo_path %>
        </td>
      </tr>
    </table>
  <% else %>
    <div class="popups">
      <%= link_to 'Coupon Preview', print_merchant_promo_path %>
     <br />
     <br />
    </div>
  <% end %>
<% end %>
<div class="coupon_details">
<% if @promo.promo_valid? %>
  <% if user_signed_in? %>
    <% unless current_user.claimed?(@promo) %>
      <p>This deal can still be claimed. Would you like to claim it?</p>
      <%= form_tag claim_merchant_promo_path(@promo.merchant, @promo) do %>
        <%= submit_tag 'Claim', :confirm => "Are you sure you want to claim the following deal?\n* #{@promo.name}" %>
      <% end %>
    <% end %>
  <% else %>
    You need to be
    <%= link_to 'signed in', new_user_session_path %>
    to claim this deal.
  <% end %>
<% else %>
  <p>Sorry! This deal cannot be claimed anymore!</p>
<% end %>
</div>

app/views/promos/_form.html.haml
= form_for([@merchant, @promo], :html => { :multipart => true, :class => "form label-top" } ) do |f|
  = render :partial => 'shared/errors', :locals => {:resource => @promo}
  .field
    = f.label :product_name
    %br
    = f.text_field :name
    %br
  .field
    = f.label :image
    %br
    = f.file_field :image
    = f.hidden_field :image_cache
  .field
    = f.label :details
    %br
    = f.text_area :details, :rows => 5, :value => "This coupon is for one-time use only and is not convertible to cash. Present this coupon to any participating branches and pay it directly." 
  Leave it Blank if you want to generate the code randomly.
  .field
    = f.label :code
    %br
    = f.text_field :manual_code
  Countdown Start must be at least 1 day from now. Countdown Period: 4 hours to 3 days.
  .field.clearfix
    .alignLeft
      = f.label(:period_start, "Countdown start")
      %br
      = f.text_field :period_start, :class => "ui-date-picker"

    .alignLeft
      = f.label( :period_end, "Countdown end")
      %br
      =  f.text_field :period_end, :class => "ui-date-picker"

  .field.clearfix
    .alignLeft
      = f.label( :coupon_validity_start, "Coupon validity start")
      %br
      = f.text_field :coupon_validity_start, :class => "ui-date-picker-no-time"

    .alignLeft
      = f.label( :coupon_validity_end, "Coupon validity end")
      %br
      = f.text_field :coupon_validity_end, :class => "ui-date-picker-no-time"
  .field
    = f.label :price_actual, 'Actual price'
    %br
    = f.text_field :price_actual
  .field
    = f.label :price_discounted, "Discounted price (discount must be #{Promo::MIN_DISCOUNT_RATE*100}% of actual price or higher)"
    %br
    = f.text_field :price_discounted
  .field
    = f.label :quota, "Quota (number of coupons to be given)"
    %br
    = f.text_field :quota

  - if admin_signed_in?
    .field.checkbox
      = f.check_box :featured
      %span Is this a featured promo?

  .field.checkbox
    = f.label(:branch, "Assign to Branch")
    %br
    -@merchant.branches.each do |branch|
      -if @promo.branch_ids.include? ( branch.id )
        =check_box_tag "branches[#{branch.id}]", 1, true
      -else
        =check_box_tag "branches[#{branch.id}]"
      = branch.name
      %br
    -#
      %input{ :id => "promo_branch", :name => "promo[branch][]", :type => "checkbox", :value => branch.name }
      = branch.name
      %br
      

  .buttonrow
    %button{:type => "submit", :name => 'submit'}
      %span Submit
    -if admin_signed_in? && @promo.persisted?
      %button{:type => "submit", :name => 'activate'}
        %span Activate
      %button{:type => "submit", :name => 'reject'}
        %span Reject

app/views/promos/_redeem.html.haml
-form_tag(redeem_merchant_promo_path(@promo.merchant, @promo), :method => 'put') do
  = hidden_field_tag 'user_id', user_id
  = submit_tag 'Redeem'

app/views/promos/edit.html.haml
-if admin_signed_in? || @merchant == current_merchant
  %h3 Edit Deal
  #inline-form.portlet-content
    = render :partial => 'form'

app/views/promos/index.html.haml
.portlet-header
  %h4 Latest Deals
  %ul.portlet-tab-nav
    =link_to_collection 'All', root_path
    -@classifications.each do |c|
      -link_to_collection c.name, classified_promos_path(:classification => c.permalink), c.permalink
.portlet-content
  =will_paginate
  -@promocount
  -@promos_next_count
  -if @promocount != 0
    -@promos.each do |deal|
      -if deal.date_now >= deal.countdown_period_start && deal.promo_valid?
        .deal-item
          %h3#dealname=link_to "Only P#{deal.price_discounted} for #{deal.name.capitalize} at #{deal.merchant.name.capitalize}", [deal.merchant, deal]
          .deal-index.round  
            %table#box
              %tr
                %td#box
                  %b Actual:
                %td#box
                  %b Discount:
                %td#box
                  %b Savings:
              %tr
                %td#box2
                  %b= "P#{deal.price_actual}"
                %td#box2
                  %b= "#{deal.percent_discounted}%"
                %td#box2
                  %b= "P#{deal.price_actual - deal.price_discounted}"
            %table#box     
              %tr
                %td#box
                  %b Time to claim:
              %tr
                %td
                .countdown.index.round
                  =deal.countdown_time_left
          .remaining-show2.round
            %table
              %tr
                %td#box4
                  = "#{deal.remaining} coupons left"
                %td#box3.round
                  =link_to "claim it!", [deal.merchant, deal]
          .deal-item-image#gallery2
            = link_to image_tag(deal.image.url || '/images/deal.default2.png'), [deal.merchant, deal]
          .remaining-coupons2.round
            %br
          .deal-details2
            -if admin_signed_in? || deal.merchant == current_merchant
              %p
                %strong Manage this deal:
                = link_to('Show Records', [deal.merchant, deal])
  -else
    -if @promos_next_count == 1 || @promos_next_count != 0
      %h2#details1
        Bringing Online Deals to Baguio City! Sign Up for FREE to grab the Deals.
      %br
      .deal-index1.round  
        %table#box1   
          %tr
            %td#box
              %b The Next Deal is coming up in about: 
          %tr
            %td#box1
              .countdown.index1.round
                =@promos_coming.countdown_for_next_deal
    -elsif @promos_next_count == 0
      %h2#details1
        -#You missed the Recent Deal. Please wait for the Next One.
        Bringing Online Deals to the Philippines 
      %h4#details1
        You can now sign up for FREE. Please wait for more updates about the deals.
  =will_paginate

app/views/promos/new.html.haml
- if admin_signed_in? || @merchant == current_merchant
  %h3 New Deal
  #inline-form.portlet-content
    = render :partial => 'form'

app/views/promos/print.html.erb
<html>
  <head>
    <%#= stylesheet_link_tag 'print' %>
    <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js' %>
    <%= javascript_include_tag 'rails' %>
    <%= javascript_include_tag 'jquery.printPage.js' %>
    <%= javascript_include_tag 'print.js' %>
  </head>
  <body>

    <div id="container">
      <div style="width: 100%; margin: 0 auto;">
        <table style="width: 483; border-style: dashed; border-width: 2;">
          <tr>
            <td>
              <% unless @promo.image.url %>
                 <%= image_tag "deal.default2.png", :height => "80px", :weight => "80px" %>
              <% else %>
                 <%= image_tag @promo.image.url, :height => "80px", :weight => "80px" %>
              <% end %>
            </td>
            <td style="width: 350; text-align: center;">
              <b>TWIGGZY COUPON</b><br />
              <span style="font-size: 8;">www.twiggzy.com<span>
                </td>
                <td>
                  <% unless @promo.merchant.image.url %>
                    <%= image_tag "merchant.default.png", :height => "100px", :weight => "100px" %>
                  <% else %>
                    <%= image_tag @promo.merchant.image.url, :height => "80px", :weight => "80px" %>
                  <% end %>
                </td>
              </tr>
              <tr>
                <td colspan="3">
                  <center style="font-size: 10;">
                    <b><%= @promo.merchant.name %></b> is exclusively offering <% @promo.promo_claims.each do |claim| %><b><u><% if claim.user.first_name == current_user.first_name && claim.user.last_name == current_user.last_name%><%= claim.user.first_name.capitalize %> <%= claim.user.last_name.capitalize %></b><% end %></u><% end %>
                    <br />
                    <b><%= @promo.name.capitalize %></b> from the original price of <b>P<%= @promo.price_actual %></b> to discounted price of <b>P<%= @promo.price_discounted %></b>.
                    <br />
                    <% if user_signed_in? && current_user.claimed?(@promo) %>
                      CODE: 
                      <% if @promo.manual_code.nil? %>
                        <b><%= @promo.random_code %></b>
                      <% else %>
                        <b><%= @promo.manual_code %></b>
                      <% end %>
                    <% end %>
                  </center>
                </td>
              </tr>
              <tr>
                <td colspan="3" style="font-size: 9;">
                  <br />
                  &nbsp; The deal is valid only from <b><%= @promo.coupon_validity_start.strftime("%B %d, %Y") %></b> to <b><%= @promo.coupon_validity_end.strftime("%B %d, %Y") %></b>.<br />
                  &nbsp; Selected branch: 
                  <b>
                    <% @merchant.branches.each do |branch| %>
                      <%= branch.name %>, <%= branch.address.capitalize %>, <%= branch.city.name.capitalize %> (tel no. <%= branch.contact_number %>),
                    <% end %>
                  </b>
                </td>
              </tr>
              <tr>
                <td colspan="3" style="font-size: 9; text-align: center;">
                  <br />
                  &nbsp; <b>Present this coupon and pay directly to the merchant.</b><br />
                  <b>
                  </b>
                </td>
              </tr>        
            </table>
          </div>
      </div>
      <div>
	    </br>
	    <table style="width: 483; font-size: 10;">
		   <tr>
			  <td>
				Details:
			  </td>	
			</tr>
			<tr>
			  <td>
				<%= @promo.details %>
			  </td>		
			</tr>	
		</table>
	  </div>
  </body>
</html>

app/views/promos/records.html.haml
-if merchant_signed_in?
  -if @promos.empty?
    %h2 Missing deal
    %p
      You haven't created any deal yet.
      =link_to 'Click here ', new_merchant_promo_path(current_merchant)
      to create one.
  -else
    #claimed-deals
      %h1
        Listing deals owned by
        = current_merchant.name
      %table{:cellspacing => 0, :cellpadding => 0}
        %tr
          %th Deal Name
          %th Claim Period Status
          %th Authentication Code
        -@promos.each do |deal|
          %tr
            %td= link_to deal.name, [deal.merchant, deal]
            %td{:class => deal.status}
              =deal.status.to_s.humanize
            %td= deal.manual_code
-elsif admin_signed_in?
  -if @promos.empty?
    %h2 No pending deals
    %p There are no pending deals as of the moment.
  -else
    #claimed-deals
      %h1
        Listing all pending deals
      %table{:cellspacing => 0, :cellpadding => 0}
        %tr
          %th Deal Name
          %th Claim Period Status
          %th Authentication Code
        -@promos.each do |deal|
          %tr
            %td= link_to deal.name, [:edit, deal.merchant, deal]
            %td{:class => deal.status}
              =deal.status.to_s.humanize
            %td= deal.manual_code

app/views/promos/track.html.haml
-if @promos.empty?
  %h2 You haven't claimed any deal yet.
  %p
    =link_to 'Click here', root_url
    to look for great deals!
-else
  #claimed-deals
    %h1
      Listing deals claimed by
      =@current_user.first_name
      =@current_user.last_name
    %p
      ="Hi #{@current_user.first_name}! The following table lists the deals you have claimed so far. To use them, print their corresponding coupons and present them the next time you go to their merchants. You can print a coupon by clicking the name of the deal you wish to redeem below. It will take you to that deal's page. From there, simply click the print button. Enjoy!"
    %table{:cellspacing => 0, :cellpadding => 0}
      %tr
        %th Deal Name
        %th Deal Validity
        %th Authentication Code
      -@promos.each do |deal|
        %tr
          %td
            = link_to deal.promo.name, [deal.promo.merchant, deal.promo]
          %td= deal.validity
          %td= deal.manual_code || deal.random_code