config/routes.rb
Promosite::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'
  match '/signin' => 'authentications#new', :as => :signin
  match '/auth/failure' => 'authentications#failure'
  devise_for :admins
  devise_for :users, :controllers => {:registrations => 'user_registrations'}
  devise_for :merchants, :controllers => {
    :registrations => 'merchant_registrations'}

  resources :authentications
  resources :cities
  resources :classifications
  resources :merchants do
    resources :branches
    resources :promos do
      post :claim, :on => :member
      put :redeem, :on => :member
      match '/print', :to => 'promos#print', :on => :member
    end
  end

  match '/privacy',      :to => 'pages#privacy'
  match '/term_use',     :to => 'pages#term_use'
  match '/term_sale',    :to => 'pages#term_sale'
  match '/how_it_works', :to => 'pages#how_it_works'
  
  match '/my_promos',  :to => 'promos#track',   :as => 'claimed_promos'
  match '/my_tracker', :to => 'promos#records', :as => 'promo_records'

  match 'promos/:classification', :to => 'promos#index',
    :as => 'classified_promos'
  
  match '/merchants/classified-as/:classification',
    :to => 'merchants#index',
    :as => 'classified_merchants' 

  root :to => "promos#index"
end

app/models/classification.rb
class Classification
  include Mongoid::Document
  field :name,      :type => String
  field :permalink, :type => String
  
  references_many :promos #try promos to make merchants classification as reference
  references_and_referenced_in_many :merchants, :inverse_of => :classifications
  
  validates :name,
    :presence => true,
    :uniqueness => true

  before_save :create_permalink

  private

    def create_permalink
      self.permalink = self.name.parameterize
    end
end

app/controllers/classifications_controller.rb
class ClassificationsController < ApplicationController
  before_filter :authenticate_admin!
  
  
  # GET /classifications
  # GET /classifications.xml
  def index
    @classifications = Classification.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @classifications }
    end
  end

  # GET /classifications/1
  # GET /classifications/1.xml
  def show
    @classification = Classification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @classification }
    end
  end

  # GET /classifications/new
  # GET /classifications/new.xml
  def new
    @classification = Classification.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @classification }
    end
  end

  # GET /classifications/1/edit
  def edit
    @classification = Classification.find(params[:id])
  end

  # POST /classifications
  # POST /classifications.xml
  def create
    @classification = Classification.new(params[:classification])

    respond_to do |format|
      if @classification.save
        format.html { redirect_to(@classification, :notice => 'Classification was successfully created.') }
        format.xml  { render :xml => @classification, :status => :created, :location => @classification }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @classification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /classifications/1
  # PUT /classifications/1.xml
  def update
    @classification = Classification.find(params[:id])

    respond_to do |format|
      if @classification.update_attributes(params[:classification])
        format.html { redirect_to(@classification, :notice => 'Classification was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @classification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /classifications/1
  # DELETE /classifications/1.xml
  def destroy
    @classification = Classification.find(params[:id])
    @classification.destroy

    respond_to do |format|
      format.html { redirect_to(classifications_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/classifications/_check_box_item.html.erb
<% if classified.classification_ids.include?( check_box_item.id ) %>
  <%= check_box_tag "classifications[#{check_box_item.id}]", 1, true %>
<% else %>
  <%= check_box_tag "classifications[#{check_box_item.id}]" %>
<% end %>
<%= check_box_item.name  %>
<br />

app/views/classifications/_check_boxes.html.erb
<% if @classifications %>
  <%= render :partial => 'classifications/check_box_item', :collection => @classifications,
    :locals => { classified: classified } %>
<% end %>

app/views/classifications/_form.html.erb
<%= form_for(@classification) do |f| %>
  <% if @classification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classification.errors.count, "error") %> prohibited this classification from being saved:</h2>

      <ul>
      <% @classification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/classifications/edit.html.erb
<h1>Editing classification</h1>

<%= render 'form' %>

<%= link_to 'Show', @classification %> |
<%= link_to 'Back', classifications_path %>

app/views/classifications/index.html.erb
<h1>Listing classifications</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @classifications.each do |classification| %>
  <tr>
    <td><%= classification.name %></td>
    <td><%= link_to 'Show', classification %></td>
    <td><%= link_to 'Edit', edit_classification_path(classification) %></td>
    <td><%= link_to 'Destroy', classification, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Classification', new_classification_path %>

app/views/classifications/new.html.erb
<h1>New classification</h1>

<%= render 'form' %>

<%= link_to 'Back', classifications_path %>

app/views/classifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @classification.name %>
</p>


<%= link_to 'Edit', edit_classification_path(@classification) %> |
<%= link_to 'Back', classifications_path %>